require "../core/widget"
require "../core/types"
require "../core/font_sizing"
require "../dsl/primitive_builder"
require "./text_input"
require "./combo_box_popup"
require "./popup_host"

module CrymbleUI
  # ComboBox widget - dropdown with text input and filtered popup
  #
  # NEW Architecture (collapsed/expanded states):
  # - COLLAPSED: NO children, renders "»{value}" as primitives
  # - EXPANDED: Popup (overlay) contains TextInput + filtered list
  #
  # The TextInput only exists inside the popup when expanded.
  #
  # ## Usage
  #
  # ```crystal
  # combo_box(items: ["Apple", "Banana", "Cherry"], selected: 0) do |index, value|
  #   puts "Selected: #{value} at index #{index}"
  # end
  # ```
  #
  # ## Editable mode (opt-in)
  #
  # By default a ComboBox can only commit one of its `items`. Pass
  # `editable: true` and submitting text that matches no item commits it as a
  # custom value — `on_select` fires with `ComboBoxPopup::CUSTOM_INDEX` (-1) and
  # the typed string, and the collapsed cell displays it. Used where the list is
  # a set of *suggestions* rather than the only valid answers (e.g. resolving a
  # merge conflict to a value that is neither candidate). Leave it off where the
  # value must be an existing item (e.g. reference cells).
  class ComboBox < Widget
    include PrimitiveBuilder
    include PopupHost

    # Layout constants
    BORDER_WIDTH = 1.0
    PADDING      = 4.0
    MIN_WIDTH = 80.0
    FONT_SCALE = 0  # Default font scale (uses FontSizing)

    # Items in the dropdown
    @items : Array(String)

    # Currently selected index (reactive_property + reconcile for auto state preservation)
    reactive_property selected_index : Int32 = 0, reconcile: true

    # When editable, a committed value not in @items (free-typed) is kept here so
    # the collapsed cell can display it; reconcile so it survives a DSL
    # rebuild like selected_index does. nil for a normal item pick.
    reactive_property custom_text : String? = nil, reconcile: true

    # Opt-in: when true, the popup commits free-typed text that matches no item
    # as a custom value (CUSTOM_INDEX) instead of cancelling. Default combos —
    # e.g. reference cells, whose value must be an existing item — stay off.
    @editable : Bool = false

    # Popup reference (NOT a child - uses Window.overlays)
    @current_popup : ComboBoxPopup?

    # Popup open state (reactive_property + reconcile for auto state preservation)
    reactive_property popup_open : Bool = false, reconcile: true

    # Guard flag: true while expand() is transferring focus to popup's TextInput
    @expanding : Bool = false

    # Saved proxy-focus state: true if we had proxy focus when expand() was called.
    # Needed because on_blur → clear_proxy_focus resets @proxy_focused before collapse() runs.
    @was_proxy_focused : Bool = false

    # Explicit width
    @explicit_width : Float64?

    # Text background colors for dropdown items
    reactive_property text_background_color : Color?
    reactive_property text_background_colors : Array(Color)?

    # Collapsed-cell background override. When nil, the collapsed ComboBox
    # uses Theme.current.combo_background; when set, it uses this color.
    # Used e.g. to tint a highlighted cell (such as a changed/diff cell).
    reactive_property background_color : Color?

    # Selection callback
    @on_select : Proc(Int32, String, Nil)?

    # Collapsed state (inverse of popup_open for clarity)
    def collapsed? : Bool
      !popup_open
    end

    # Expose popup state for testing (Crystal convention: ? suffix for bool)
    def popup_open? : Bool
      popup_open
    end

    def current_popup : ComboBoxPopup?
      @current_popup
    end

    # Note: selected_index and popup_open getters are also generated by reactive_property

    # True when `i` addresses a real list item, vs. a custom (editable) value
    # which is signalled by an out-of-range index such as ComboBoxPopup::CUSTOM_INDEX.
    private def item_index?(i : Int32) : Bool
      i >= 0 && i < @items.size
    end

    def selected_value : String?
      if item_index?(selected_index)
        @items[selected_index]
      else
        custom_text # editable free-typed value committed out of @items range, or nil
      end
    end

    def editable? : Bool
      @editable
    end

    # Close popup when ComboBox loses focus (e.g., Tab key)
    # But NOT when we're expanding (focus transfers to popup's TextInput)
    def on_blur

      collapse if popup_open && !@expanding
    end

    # Close popup when VirtualMatrix moves proxy focus away from this cell
    # But NOT during expand (focus transfers to popup's TextInput)
    def deactivate_proxy_focus
      collapse if popup_open && !@expanding
      super
    end

    def items : Array(String)
      @items
    end

    # ComboBox has NO children (TextInput is in the popup when expanded)
    # We don't add anything to @children in initialize, so children is already empty

    # ComboBox is focusable (receives keyboard input)
    def focusable? : Bool
      true
    end

    def initialize(
      items : Array(String),
      selected : Int32 = 0,
      width : Float64? = nil,
      id : String? = nil,
      text_background_color : Color? = nil,
      text_background_colors : Array(Color)? = nil,
      background_color : Color? = nil,
      editable : Bool = false,
      &block : Int32, String -> Nil
    )
      @text_background_color = Source(Color?).new(text_background_color)
      @text_background_colors = Source(Array(Color)?).new(text_background_colors)
      @background_color = Source(Color?).new(background_color)
      super(id: id)
      @items = items
      @selected_index = Source(Int32).new(items.empty? ? -1 : selected.clamp(0, items.size - 1))
      @_build_selected_index = selected_index
      @explicit_width = width
      @editable = editable
      @on_select = block
      # NO TextInput child - it's in the popup when expanded
    end

    # Constructor without callback
    def initialize(
      items : Array(String),
      selected : Int32 = 0,
      width : Float64? = nil,
      id : String? = nil,
      text_background_color : Color? = nil,
      text_background_colors : Array(Color)? = nil,
      background_color : Color? = nil,
      editable : Bool = false
    )
      @text_background_color = Source(Color?).new(text_background_color)
      @text_background_colors = Source(Array(Color)?).new(text_background_colors)
      @background_color = Source(Color?).new(background_color)
      super(id: id)
      @items = items
      @selected_index = Source(Int32).new(items.empty? ? -1 : selected.clamp(0, items.size - 1))
      @_build_selected_index = selected_index
      @explicit_width = width
      @editable = editable
      @on_select = nil
      # NO TextInput child - it's in the popup when expanded
    end

    # Override label for path_id generation
    def label : String?
      "combo_box"
    end

    # Measure collapsed state - text "»{value}" with padding
    def measure(constraints : BoxConstraints) : Size
      display_text = "»#{selected_value || ""}"
      font_size = FontSizing.calculate_size(FONT_SCALE)
      text_size = Widget.measure_text(display_text, font_size)

      # Height: tight constraints → fill exactly; loose → natural, clamped to max.
      # (Same idiom as TextInput#measure — the two share matrix cells: a tight
      # height fills a merged VirtualMatrix row-header spanning several record
      # rows, e.g. a factored-out reference header.)
      height = text_size.height + (PADDING + BORDER_WIDTH) * 2
      if constraints.min_height == constraints.max_height && constraints.max_height.finite?
        height = constraints.max_height  # Tight: fill cell (e.g., merged VirtualMatrix cells)
      elsif constraints.max_height.finite?
        height = Math.min(height, constraints.max_height)  # Loose: clamp down only
      end

      # Width: prefer explicit, then constraint max, then natural
      width = @explicit_width || constraints.max_width
      width = Math.min(width, constraints.max_width) if constraints.max_width.finite?
      width = 200.0 if !width.finite?

      Size.new(width, height)
    end

    # Layout - no children when collapsed, position popup if expanded
    def perform_layout(constraints : BoxConstraints, position : Vec2)
      size = measure(constraints)
      @bounds = Rect.new(position, size)

      # Re-position popup if open (in Window.overlays), with the SAME flip-above logic as
      # the initial open so a rebuild while open doesn't snap it back below the cell.
      if popup_open && (popup = @current_popup)
        popup.bounds = Rect.new(popup_position(absolute_bounds, popup.bounds.height), popup.bounds.size)
      end
    end

    # Render collapsed state as primitives
    def to_primitives(bounds : Rect) : Array(DrawPrimitive)
      display_text = "»#{selected_value || ""}"
      local_bounds = Rect.new(0.0, 0.0, bounds.width, bounds.height)
      # A disabled combo renders dimmed and does not open (mirrors Button) — for
      # callers that keep the control in place when there's nothing to pick (e.g.
      # embrace's merge-source picker when no branch is mergeable).
      txt_color = Theme.current.combo_text
      txt_color = Color.new(txt_color.r, txt_color.g, txt_color.b, (txt_color.a // 3).to_u8) unless enabled?

      primitives do
        # Background — override-able so callers can tint the cell (e.g. to
        # highlight a changed cell) without losing the combo widget.
        fill_rect(local_bounds, background_color || Theme.current.combo_background)
        # Border
        draw_rect(local_bounds, Theme.current.combo_border)
        # Text (vertically centered in content area, matching TextInput alignment)
        content_y = BORDER_WIDTH + PADDING
        content_height = bounds.height - (BORDER_WIDTH + PADDING) * 2
        text_y = vcentered_text_y(content_height, FONT_SCALE, content_y)
        text_pos = Vec2.new(PADDING, text_y)
        draw_text(display_text, text_pos, txt_color, FONT_SCALE)
      end
    end

    # ========== EVENT HANDLERS ==========

    # Handle mouse up - expand when clicked on collapsed ComboBox (left-click only)
    def on_mouse_up(point : Vec2, button : MouseButton = MouseButton::Left)
      expand if collapsed? && button == MouseButton::Left
    end

    # Handle Enter/Escape keys
    def on_key_down(key : SF::Keyboard::Key, control : Bool, shift : Bool, alt : Bool = false) : Bool
      if collapsed? && (key.return? || key.enter?)
        expand
        return true
      end
      if popup_open && key == SF::Keyboard::Key::Escape
        collapse
        return true
      end
      false
    end

    # Handle text input - expand AND insert character
    def on_text_input(char : Char)

      if collapsed?
        expand(initial_char: char)
      end
    end

    # ========== EXPAND / COLLAPSE ==========

    # Expand - open popup with TextInput and filtered list
    def expand(initial_char : Char? = nil)
      return unless enabled? # disabled combos don't open
      return if popup_open


      popup = ComboBoxPopup.new(
        items: @items,
        selected_index: selected_index,
        max_height: 200.0,
        text_background_color: text_background_color,
        text_background_colors: text_background_colors,
        editable: @editable
      )

      # Wire up callbacks
      popup.on_select = ->(idx : Int32, val : String) {
        select_and_close(idx, val)
      }
      popup.on_cancel = -> {
        collapse
      }

      # Type-to-filter mode: Up/Down also close popup + navigate grid
      if initial_char
        popup.text_input.on_vertical_arrow = ->(is_down : Bool) {
          popup.select_highlighted
          if scope = focus_scope_ancestor
            key = is_down ? SF::Keyboard::Key::Down : SF::Keyboard::Key::Up
            scope.on_key_down(key, false, false)
          end
          true
        }
      end

      # Type-to-filter mode: Left/Right also close popup + navigate grid
      # In Enter/click mode: Left/Right stay in TextInput for cursor movement
      if initial_char
        popup.text_input.on_horizontal_arrow = ->(is_right : Bool) {
          popup.select_highlighted
          if scope = focus_scope_ancestor
            key = is_right ? SF::Keyboard::Key::Right : SF::Keyboard::Key::Left
            scope.on_key_down(key, false, false)
          end
          true
        }
      end

      # Tab/Shift+Tab: commit highlight + advance the grid cursor (spreadsheet Tab).
      # Mode-independent (Tab never moves the text caret), so wired unconditionally.
      wire_popup_tab_callback(popup)

      # Click-outside-to-close (notified by App.handle_mouse_down → Window.notify_overlays_of_click)
      popup.on_click_outside_callback = -> {
        collapse
      }

      mount_popup(popup)

      # Insert initial character if typed while collapsed
      if char = initial_char
        popup.text_input.insert_char(char)
      end

      # Only mark_needs_render, NOT mark_needs_layout.
      # mark_needs_layout propagates up and triggers DSL rebuild, which
      # destroys/recreates VirtualMatrix cells — killing this ComboBox
      # and orphaning the popup.  The popup is in Window overlays (not
      # ComboBox children), so no layout change is needed.
      mark_needs_render

    end

    # Collapse - close popup without selecting
    def collapse
      return if collapsed?

      unmount_popup
    end

    # Select item and close popup
    def select_and_close(index : Int32, value : String)
      self.selected_index = index
      # An out-of-@items index marks a free-typed (editable) value: keep it for
      # the collapsed display since it isn't a list item. A normal pick clears it.
      self.custom_text = item_index?(index) ? nil : value
      @on_select.try(&.call(index, value))
      collapse
    end

    # Position popup below ComboBox, flip above if near window bottom
    private def position_popup
      if popup = @current_popup
        abs = absolute_bounds
        min_width = @explicit_width || abs.width
        natural_size = popup.measure(BoxConstraints.loose(Size.new(Float64::INFINITY, 200.0)))
        popup_width = {min_width, natural_size.width}.max
        popup_constraints = BoxConstraints.loose(Size.new(popup_width, 200.0))
        popup_size = popup.measure(popup_constraints)

        popup_y = abs.y + abs.height
        if window = find_window
          if popup_y + popup_size.height > window.bounds.height
            popup_y = abs.y - popup_size.height
          end
        end
        popup.layout(popup_constraints, Vec2.new(abs.x, popup_y))
      end
    end

    # Handle item selection from popup
    private def handle_item_selected(index : Int32, value : String)
      select_and_close(index, value)
    end

    # State preservation for DSL reconciliation
    def copy_state_from(old_widget : Widget)
      # First, auto-copy all @[Reconcile] annotated properties
      # (includes selected_index, popup_open from reactive_property reconcile)
      auto_copy_reconcile_properties(old_widget)

      # Call super for base widget state (background_backend, last_constraints, focus)
      super

      return unless old_widget.is_a?(ComboBox)
      old = old_widget.as(ComboBox)

      # Copy popup and RE-WIRE callbacks to point to NEW combo box (self)
      # Without this, callbacks still reference the OLD combo box instance
      # (Can't be automated - closures capture specific object references)
      if popup_open && (popup = old.@current_popup)
        @current_popup = popup
        # Re-wire callbacks (closures capture old widget instance)
        popup.on_select = ->(idx : Int32, val : String) {
          select_and_close(idx, val)
        }
        popup.on_cancel = -> {
          collapse
        }
        popup.on_click_outside_callback = -> {
          collapse
        }
        # Re-bind Tab too, so a rebuild-while-open keeps routing Tab to THIS combo
        # (the arrow intercepts are filter-mode-gated and not preserved here).
        wire_popup_tab_callback(popup)
      end
    end

    # Wire Tab/Shift+Tab on the popup's TextInput: commit the highlighted value, then —
    # inside a focus-scope (VirtualMatrix) — re-dispatch Tab so the grid cursor advances
    # and focus stays in the matrix (return true to hold the Tab-trap); standalone,
    # return false so FocusManager cycles to the next widget. Called from expand and,
    # since closures capture this combo, re-bound from copy_state_from on DSL rebuild.
    private def wire_popup_tab_callback(popup)
      popup.text_input.on_tab = ->(shift : Bool) {
        popup.select_highlighted
        if scope = focus_scope_ancestor
          scope.on_key_down(SF::Keyboard::Key::Tab, false, shift)
          true
        else
          false
        end
      }
    end
  end
end
